cask_args appdir: '/Applications'

tap 'homebrew/bundle'

brew 'ack'
brew 'autoenv'
brew 'coreutils'
brew 'go'
brew 'grc'
brew 'imagemagick', args: ['with-webp']
brew 'jq'
brew 'openssl'
brew 'node'
brew 'nvm'
brew 'readline'
brew 'spark'
brew 'unrar'
brew 'wget'
brew 'yarn'
brew 'zsh'

cask '1password'
cask 'appcleaner'
cask 'dropbox'
cask 'imagealpha'
cask 'imageoptim'
cask 'iterm2'
cask 'rescuetime'
cask 'skype'
cask 'slack'
cask 'steam'
cask 'transmission'
cask 'visual-studio-code'
cask 'vlc'
